version: '3'

services:
  phpunit:
    build: .
    entrypoint: ./bin/phpunit.sh
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_autostart=1
        PHP_IDE_CONFIG: "serverName=ldap_phpunit"
    volumes:
      - ./:/opt/project/
  composer:
    build: .
    entrypoint: /root/bin/composer
    volumes:
      - ./:/opt/project/
  bash:
    build: .
    entrypoint: ./bin/bash.sh
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_autostart=1
      PHP_IDE_CONFIG: "serverName=ldap_bash"
      LDAP_SERVER: LOOPBACK:us.loopback.world:DC=us,DC=loopback,DC=world:OpenLDAP
    volumes:
      - ./:/opt/project/