version: '3'

services:
  phpunit:
    build: .
    entrypoint: ./bin/phpunit.sh
    environment:
        XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_autostart=1
    volumes:
      - ./:/opt/project/
  composer:
    build: .
    entrypoint: /root/bin/composer
    volumes:
      - ./:/opt/project/
  bash:
    build: .
    entrypoint: bash
    volumes:
      - ./:/opt/project/